### ISSUE TITLE
プロダクト作成機能を追加したい

### ISSUE THREAD

**Issue by popmac** [Sho-Yama/crowdfunding#3]
## 要件
ログインを行ったユーザーが自身のプロダクトを追加できるようにしたい

## 要望
ProductのModel,Controller,ViewをScaffoldで作成してみましょう

UserとProductが1対多になるようにリレーションを追加してみましょう

productsテーブルのカラムは以下でお願いします

```
title: string
desc: string
user_id: integer
```

**Comment by Sho-Yama** [comment]
リレーションの追加まで終わりました
