### ISSUE TITLE
ログインを行ったユーザーのみがProductを作成できるようにする

### ISSUE THREAD

**Issue by popmac** [Sho-Yama/crowdfunding#6]
## 依頼内容
現在の実装では、ログインしていないUserでもProductを作成できるようになっています。
こちらを、ログインしているUserだけがProductを作成できるようにする、ようにしてみましょう🙌
deviseの機能で用意されているので、調べてみるといいと思います。

また、以下のスクショのように、Productを作成する際にUserのidを直接入力する形になっています。

![スクリーンショット 2019-09-24 11 10 39](https://user-images.githubusercontent.com/19648958/65475850-fc9e6380-debb-11e9-9cd6-1fd09932aabb.png)

このフォームではUserのidを入力しなくていいようにしてみましょう。

## Todo
まとめると以下がタスクになります。

- ログインしているUserだけがProductを作成できるようにする
- Productを作成する際にフォームではUserのidは入力しないようにする

疑問などがありましたら、ご連絡ください👍

**Comment by Sho-Yama** [comment]
一通りできました。確認お願いします。
